### ISSUE TITLE
EDA

### ISSUE THREAD

**Issue by hsmohammed** [UBC-MDS/522_group-33#23]
- There is class imbalance in the dataset. You can explain how to deal with this and how could that affect the results? You could do that in the EDA file or in the proposal.

**Comment by athy9193** [comment]
Hi Hossam, thank you for your feedback, to address the data imbalance, we decided to use f1-score as our metric to analysis the data. We hope that this is ok. Again, we do appreciate your feedback to help us improve further.
Best,
Group 33
