### ISSUE TITLE
Research Question and the data set to use

### ISSUE THREAD

**Issue by BruhatMusunuru** [UBC-MDS/522_group-33#3]
Please add all your suggestions for the Research Question and the data set to use so it's easier to keep track and vote on one.

**Comment by BruhatMusunuru** [comment]
While browsing through the link sang posted on slack, I found a simple data set on cars. It's a multi class categorical classification problem which could be a good start point where we can evaluate if we want to go with something more complex and asses the difficulty we are comfortable with.  https://archive.ics.uci.edu/ml/datasets/Car+Evaluation

**Comment by athy9193** [comment]
## Links on data sets:
Google Mobility Dataset: https://www.google.com/covid19/mobility/

John Hopkins Covid-19 cases data
* Overall GitHub repo: https://github.com/CSSEGISandData/COVID-19
* Time series data: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series
* Example on one raw dataset: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv
* Dashboard: https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Apple Covid19-Mobility Dataset: https://covid19.apple.com/mobility
(as back-up, I would prefer Google data as Google maps is more widely used)

Wine quality Dataset: https://archive.ics.uci.edu/ml/datasets/wine+quality
