### ISSUE TITLE
Maybe make a cartoon for “poor”, “normal” and “excellent” for scale “1-4”, “5-6” and “7-9”.

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/522_group-33#42]

**Comment by athy9193** [comment]
Hi @ericlee0920 , thank you for the comment, we draft the following cartoon/diagram. Is this roughly what you have in mind? 
![image](https://user-images.githubusercontent.com/56498756/101234338-4fe38700-36f9-11eb-8988-98665e5d4aee.png)

**Comment by ericlee0920** [comment]
This is good!

**Comment by athy9193** [comment]
Hi @ericlee0920, the diagram has been incorporated in our report accordingly [here](https://github.com/UBC-MDS/Wine_Quality_Predictor/blob/main/reports/reports.md) Thank you.
