### ISSUE TITLE
From the looks of table 1, you may want to give a sanity check on random forest.

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/522_group-33#43]

**Comment by BruhatMusunuru** [comment]
After looking at the results, MLP and random forests seem to be the best models for our data. But after analysing the models, We concluded that Random forests is picking up noise in the data as the train error is comparatively drastically lower than the validation error. This is a sign of over fitting which does not seem to affect MLP. Furthermore, the cross-validation scores are more consistent and normally distributed compared to Random forests which further cements that MLP is the best pick.
