### ISSUE TITLE
Maybe have a table that gives percentages for your confusion matrix? Seems like a imbalance in data and not well described cases of the upper left of the matrix.

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/522_group-33#44]

**Comment by rissangs** [comment]
Hi, @ericlee0920,

Thank you for your comment. We have changed a table as it gives a percentage for the confusion matrix. 

Please check [here](https://github.com/UBC-MDS/Wine_Quality_Predictor/blob/main/reports/reports.md).
