### ISSUE TITLE
Maybe a plot for 1599 observations for red wine and 4898 observations of white wine in a bar plot? - overall good work!

### ISSUE THREAD

**Issue by ericlee0920** [UBC-MDS/522_group-33#46]

**Comment by wang-rui** [comment]
Hi @ericlee0920, 

We actually had a bar chart [here](https://github.com/UBC-MDS/Wine_Quality_Predictor/blob/main/eda/wine_EDA.md#distribution-of-wine-type). Is this you what you want? 

Or do you mean we need to create a histogram for red wine with “Good, Normal, Excellent”  number count, and a histogram for white wine with “Good, Normal, Excellent” number count?

Thank you

**Comment by ericlee0920** [comment]
It's all good then! A good idea of how to plot information so it maximizes understanding is the most important concept.
