### ISSUE TITLE
Peer Review 

### ISSUE THREAD

**Issue by jordanlau123** [UBC-MDS/522_group-33#57]
Hey! I've taken a look at your project and found your topic very interesting and overall very well done! 

Below are just some minor details and quick suggestions I have: 

Documentation: Looks good! Everything is organized with proper names and labels. 

Code: Its Great! Code is clean and readable. 

Analysis and reasoning: 
- I would suggest exporting your scores table as a csv/pickle as opposed to a png. 
- Having a bit of EDA for the features before diving into the analysis would be helpful.
- I don't see the final test score in the results section of the report. 
- I see that there's `mean_test_f1` and `mean_test_accuracy` along with `mean_train_f1` and `mean_train_accuracy`, what is the difference between the pairs? They seem to have identical numbers. If they are identical, removing the last 2 columns would be a good idea. 

Communication: 
- Report could use a quick proof-read to fix grammar mistakes for better flow when reading. 

Overall, project is solid and well done. Keep up the good work!

**Comment by athy9193** [comment]
Hi @jordanlau123 , thank you very much for your feedback. We have tried to incorporated your suggested in our report [here](https://github.com/UBC-MDS/Wine_Quality_Predictor/blob/main/reports/reports.md)

In specific:
* We redo our Table 1 to a bar chart to improve the visual engagement of our report. We are focusing on f1 score as the data is imbalance, we have remove the accuracy column as suggested
* The test f-1 score have been added in the report

Thank you again! 

Cheers,
Group 33
