### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by dusty736** [UBC-MDS/522_group-33#61]
Hi all!  Here's my peer review for your project:

Suggestions:
1. Add a little bit to the introduction about the metric that is the output of the model?  It's referenced, but talking about the type of classification would be great.
2. Can you discuss in the data section how the binning of the target variables was decided?  Maybe a quick plot showing the distributions of the original ratings so we can get a better sense of class imbalance.
3. Can you elaborate on the 13% error rate?  It was clear why we're seeing it (class imbalance and such), but it wasn't so clear as to where it was coming from in your tables/plots.  I might have just missed that.

Summary:  Wow!  This is an awesome project.  Very well documented, great plots, and interesting model (hopefully a sneak preview of a later class).  Great job, and I might need to use this model's results before the next time I purchase wine.

**Comment by BruhatMusunuru** [comment]
Thanks for your Feedback. 

1. We have added info to our report on why we are using the f1 micro and the justification on why we consider it's the best metric.
2. We added a plot to explain the binning in the final report.
3. We have changed our strategy in explaining the error. We are now more concentrated in explaining the normalised confusion matrix and the false positives and false negatives. We also found the 13%  a bit confusing as it was calculated manually and not really reproduce able.
