### ISSUE TITLE
Peer review by Pan Fan

### ISSUE THREAD

**Issue by pan1fan2** [UBC-MDS/522_group-33#65]
Hi Team,

Big congrats, I enjoy reading this report. The repo is well structured and you can find my feedback on the latest release of your work below. 

• Documentation: Both the repo headers and the project folders have clear names. I find no issue finding my way around the repo.

• Code: Well written and easy to be understood. The code clearly shows how the analysis is done at various stages. It also takes “randomstate” into account while training the model, as a result, it has well addressed the reproducibility. I found no trouble running the code.

• Analysis and reasoning: Again, a well-written report. It provides descriptions of the issue and good reasoning why/how the machine learning model is picked. In the end, some potential improvements have also been given. Besides, the model performs well with relatively high accuracy and f1 scores. Below listed my questions/suggestions for each section in the report: 

1.	Summary
For clarity, I would suggest adding a brief explanation on the choice of the metric for assessment. Why do you decide to use accuracy and weighted f1? Because you care about f1 scores for all classes?
2.	Analysis 
It mentions class imbalance. The total amount of poor wine is significantly smaller than the Normal and Excellent ones or the other way around? It is not clear to the readers, so I would suggest adding a plot to show the distribution of wine of different rankings. 
3.	Results & Discussion
	To me, the boxplots are more like part of EDA and it might help decide the important features. I suggest moving this part to the Analysis section.
	Both bar charts have the same name for x-axis, I assume it is a typo. It mentions the bar chart shows the CV scores. I am wondering they are referring to the training or validation scores?
	I would suggest using cleassification_report to show the classification metrics. I find it difficult to tell the error rate and/or f1 scores from the confusion_matrix. 

• Communication: The language is concise and clear to me. Plots can serve the purpose.

**Comment by BruhatMusunuru** [comment]
Thanks for the feedback. We will be sure to make necessary changes based on your suggestions.
