### ISSUE TITLE
2nd meeting minutes

### ISSUE THREAD

**Issue by wang-rui** [UBC-MDS/522_group-33#7]
2020-11-19 7pm Beijing time

**Discussed a few possible ideas for project proposals**
1. Bruhat walked through cars data from UCI
2. Alex explained COVID-19 data
3. Sang Yoon discussed wine data and Rui discussed about other UCI dataset

All agreed on exploring more on COVID-19 and wine data set. 
Alex to put the links of the dataset in comment section below.

**Checked and Merged PR from last meeting**

-  Team Contract by Alex

-  Code of Conduct by Rui 

-  License by Sang Yoon

-  Contribution File by Bruhat

**Pending Tasks for next meeting**

- [ ] Explore COVID-19 or other interesting dateset and conduct EDA
- [ ]  Identify one main predictive or inferential research question that you will attempt to answer with analyses and visualizations (more on this below)
- [ ] Make a plan of how you will analyze the data (report an estimate and confidence intervals? hypothesis test? classification with a decision tree?). Choose something you already learned how to do in another MDS course.
- [ ] Discuss at least one exploratory data analysis (EDA) table and one exploratory data analysis figure you will create that makes sense for your research question, the data that you have, and the analysis you plan to do.
- [ ] Suggest how you would share the results of your analysis as one or more tables and/or figures.

    **Next meeting time: 2020-11-20 3 pm Beijing time**

**Comment by athy9193** [comment]
## Links on data sets:
Google Mobility Dataset: https://www.google.com/covid19/mobility/

John Hopkins Covid-19 cases data
* Overall GitHub repo: https://github.com/CSSEGISandData/COVID-19

* Time series data: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

* Example on one raw dataset: https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv

* Dashboard: https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6

Apple Covid19-Mobility Dataset: https://covid19.apple.com/mobility
(as back-up, I would prefer Google data as Google maps is more widely used)

Wine quality Dataset: https://archive.ics.uci.edu/ml/datasets/wine+quality
